# Generated by Django 4.2.11 on 2024-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle', max_length=255, null=True)),
                ('body', wagtail.fields.StreamField([('alert_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title')), ('description', wagtail.blocks.RichTextBlock(label='Column', required=False))])), ('raw_html_block', wagtail.blocks.RawHTMLBlock()), ('richtext_block', wagtail.blocks.RichTextBlock(template='blocks/richtext.html'))], blank=True, verbose_name='Page content block')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=255)),
                ('logo', models.URLField(blank=True, help_text='Logo image from current website', null=True)),
                ('logo_mono', models.URLField(blank=True, help_text='Monochrome logo image from current website', null=True)),
                ('favicon', models.URLField(blank=True, help_text='Favicon image from current website', null=True)),
                ('primary_color', models.CharField(default='#000000', help_text='Primary color in hexadecimal format (#RRGGBB)', max_length=7)),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter page URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram page URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube page URL', null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('site_map', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
